site_name: Database Design and Development

nav:
    - Home: 'index.md'
    - Database Structure: 
      - Flat File Databases: '1.0-database-structure.md'
      - Relational Databases: '1.1-relational-databases.md'
      - Fields: '1.2-field-types.md'
      - Primary Keys: '1.3-primary-keys.md'
      - Foreign Keys: '1.4-foreign-keys.md'
      - How Tables Link: '1.5-how-tables-link.md'
    - Analysis:
      - End User and Functional Requirements: '2.0-analysis.md'
      - Data Protection: '2.3-General-Data-Protection-Regulation.md'
    - Design: 
      - Database Relationships: '3.1-DB-Relationships.md'
      - Data Dictionairies: '3.2-Data-Dictionaries.md'
      - Query Design: '3.3-Query-Design.md'
    - Implementation:
      - SQL Select: '4.1-SQL-Select.md'
      - SQL Insert, Update, Delete: '4.2-SQL-Insert.md'
      - SQL Joins: '4.3-SQL-Equi-Joins.md'
    - Testing: '5.1-DB-Testing.md' 
    - Evaluation: '5.2-DB-Evaluation.md' 
    

markdown_extensions:
      - admonition
      - pymdownx.details
      - def_list
      - pymdownx.critic
      - pymdownx.caret
      - pymdownx.keys
      - pymdownx.mark
      - pymdownx.tilde
      - attr_list
      - md_in_html    
      - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
      - pymdownx.superfences
      - pymdownx.tabbed:
          alternate_style: true
      - pymdownx.highlight:
          use_pygments: true
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
      - pymdownx.inlinehilite
      - pymdownx.snippets
      
theme:
  name: material
  font:
    text: Quicksand
  palette: 
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - navigation.path
    #- navigation.footer
    - navigation.tabs
plugins:
  - glightbox

copyright: Copyright &copy; 2025 Pixel&Wood Computer Science Tuition

extra_css:
  - Styles/extra.css


    
